"""add_cascade_to_tables

Revision ID: 4617bf666df7
Revises: 3a84db13ce84
Create Date: 2024-01-28 13:13:56.423090

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '4617bf666df7'
down_revision: Union[str, None] = '3a84db13ce84'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('cat_images_storage_file_id_fkey', 'cat_images', type_='foreignkey')
    op.drop_constraint('cat_images_cat_id_fkey', 'cat_images', type_='foreignkey')
    op.create_foreign_key(None, 'cat_images', 'storage_files', ['storage_file_id'], ['id'], ondelete='CASCADE')
    op.create_foreign_key(None, 'cat_images', 'cats', ['cat_id'], ['id'], ondelete='CASCADE')
    op.drop_constraint('cats_owner_id_fkey', 'cats', type_='foreignkey')
    op.drop_constraint('cats_breed_id_fkey', 'cats', type_='foreignkey')
    op.create_foreign_key(None, 'cats', 'users', ['owner_id'], ['id'], ondelete='CASCADE')
    op.create_foreign_key(None, 'cats', 'breeds', ['breed_id'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'cats', type_='foreignkey')
    op.drop_constraint(None, 'cats', type_='foreignkey')
    op.create_foreign_key('cats_breed_id_fkey', 'cats', 'breeds', ['breed_id'], ['id'])
    op.create_foreign_key('cats_owner_id_fkey', 'cats', 'users', ['owner_id'], ['id'])
    op.drop_constraint(None, 'cat_images', type_='foreignkey')
    op.drop_constraint(None, 'cat_images', type_='foreignkey')
    op.create_foreign_key('cat_images_cat_id_fkey', 'cat_images', 'cats', ['cat_id'], ['id'])
    op.create_foreign_key('cat_images_storage_file_id_fkey', 'cat_images', 'storage_files', ['storage_file_id'], ['id'])
    # ### end Alembic commands ###
